name: listenbrainz_dart
description: A ListenBrainz API client for Dart.
version: 0.0.4
repository: https://github.com/takeoutfm/listenbrainz_dart

environment:
  sdk: ^3.1.0

dependencies:
  json_annotation: ^4.8.1
  http: ^1.1.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.21.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
